import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/providers/themeProvider";
import AuthProvider from "@/providers/authProvider";
import GlobalStateProvider from "@/context";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <GlobalStateProvider>
            <ThemeProvider>
              <Header />
              {children}
            </ThemeProvider>
          </GlobalStateProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
